// packages/theme-studio/vue/ThemeGeometryInput.vue
<script setup lang="ts">
defineOptions({ inheritAttrs: false });
import { ref, watch } from 'vue';
import { bindBorderInput, type Target, type BorderKind } from '../core';
import { useTheme, useThemeStore } from './context';
const props = withDefaults(
  defineProps<{ kind?: BorderKind; target?: Target; disabled?: boolean }>(),
  { kind: 'radius', target: 'DEFAULT' },
);
const store = useThemeStore(),
  state = useTheme(),
  element = ref<HTMLInputElement>();
const vInitialValue = {
  getSSRProps: (binding: { value: number }) => ({ value: binding.value }),
};
const initial =
  store.getSnapshot().theme.structure.websitePreset.border[props.kind][
    props.target
  ];
watch(
  [element, () => props.kind, () => props.target],
  ([node], _old, cleanup) => {
    if (!node) return;
    const fields = store.registerFields({
        roles: [],
        [props.kind]: [props.target],
      }),
      stop = bindBorderInput(node, store, props.kind, props.target);
    cleanup(() => {
      stop();
      fields.destroy();
    });
  },
  { flush: 'post' },
);
defineExpose({ element });
</script>
<template>
  <input
    type="number"
    min="0"
    max="1000"
    :step="kind === 'radius' ? 0.125 : 1"
    :aria-label="`${target} ${kind}`"
    v-initial-value="initial"
    v-bind="$attrs"
    ref="element"
    :disabled="disabled || state.disabled"
    data-tk-part="geometry-input"
  />
</template>

// packages/theme-studio/svelte/ThemeGeometryInput.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import type { HTMLInputAttributes } from 'svelte/elements';
  import { bindBorderInput, type Target, type BorderKind } from '../core';
  import { useTheme, useThemeStore } from './context';
  let {
    kind = 'radius',
    target = 'DEFAULT',
    disabled = false,
    ref = $bindable(),
    ...attributes
  }: Omit<HTMLInputAttributes, 'value'> & {
    kind?: BorderKind;
    target?: Target;
    ref?: HTMLInputElement;
  } = $props();
  const store = useThemeStore(),
    theme = useTheme();
  const initial = untrack(
    () =>
      store.getSnapshot().theme.structure.websitePreset.border[kind][target],
  );
  $effect(() => {
    if (!ref) return;
    const fields = store.registerFields({ roles: [], [kind]: [target] });
    const stop = bindBorderInput(ref, store, kind, target);
    return () => {
      stop();
      fields.destroy();
    };
  });
</script>

<input
  type="number"
  min="0"
  max="1000"
  step={kind === 'radius' ? 0.125 : 1}
  aria-label={`${target} ${kind}`}
  {...attributes}
  bind:this={ref}
  value={initial}
  disabled={disabled || $theme.disabled}
  data-tk-part="geometry-input"
/>
