// packages/theme-studio/vue/ThemeProvider.vue
<script setup lang="ts">
import type { ThemeOptions, ThemeStore } from '../core';
import ThemeRoot from './ThemeRoot.vue';
import ThemeProviderContent from './ThemeProviderContent.vue';
defineOptions({ inheritAttrs: false });
defineProps<{ options?: ThemeOptions; store?: ThemeStore }>();
</script>
<template>
  <ThemeRoot :store="store" :options="options">
    <ThemeProviderContent v-bind="$attrs"><slot /></ThemeProviderContent>
  </ThemeRoot>
</template>

// packages/theme-studio/svelte/ThemeProvider.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import type { ThemeOptions, ThemeStore } from '../core';
  import ThemeRoot from './ThemeRoot.svelte';
  import ThemeProviderContent from './ThemeProviderContent.svelte';
  let {
    children,
    options = {},
    store,
    ref = $bindable(),
    ...attributes
  }: HTMLAttributes<HTMLDivElement> & {
    children: Snippet;
    options?: ThemeOptions;
    store?: ThemeStore;
    ref?: HTMLDivElement;
  } = $props();
</script>

<ThemeRoot {store} {options}>
  <ThemeProviderContent {...attributes} bind:ref
    >{@render children()}</ThemeProviderContent
  >
</ThemeRoot>
