// packages/theme-studio/react/ThemeWheel.tsx
'use client';
import { ColorWheel } from '@salyra-ui/color-picker/react';
import { useSyncExternalStore } from 'react';
import { themePickerMarkers, type Role, type ThemePickerStore } from '../core';
export function ThemeWheel({ picker }: { picker: ThemePickerStore }) {
  const state = useSyncExternalStore(
    picker.subscribe,
    picker.getSnapshot,
    picker.getServerSnapshot,
  );
  return (
    <ColorWheel
      className="tk-shared-wheel"
      label="Shared theme color wheel"
      markers={themePickerMarkers(state)}
      activeId={state.activeRole}
      onSelect={(id) => picker.selectRole(id as Role)}
      onMarkerChange={(id, hsv) => picker.setHSV(id as Role, hsv)}
    />
  );
}

// packages/theme-studio/svelte/ThemeWheel.svelte
<script lang="ts">
  import { ColorWheel } from '@salyra-ui/color-picker/svelte';
  import {
    themePickerMarkers,
    type ThemePickerStore,
    type Role,
  } from '../core';
  let { picker }: { picker: ThemePickerStore } = $props();
  const pickerState = {
    subscribe(
      run: (value: ReturnType<ThemePickerStore['getSnapshot']>) => void,
    ) {
      run(picker.getSnapshot());
      return picker.subscribe(() => run(picker.getSnapshot()));
    },
  };
</script>

<ColorWheel
  class="tk-shared-wheel"
  label="Shared theme color wheel"
  markers={themePickerMarkers($pickerState)}
  activeId={$pickerState.activeRole}
  onSelect={(id) => picker.selectRole(id as Role)}
  onMarkerChange={(id, hsv) => picker.setHSV(id as Role, hsv)}
/>
