// packages/theme-studio/vue/ThemeGenerator.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, watch } from 'vue';
import {
  ColorSurface,
  ColorViewSelect,
  ColorWheel,
  ColorFormatSelect,
  ColorMode,
  ColorProvider,
  ColorArea,
  ColorSlider,
  ColorInput,
} from '@salyra-ui/color-picker/vue';
import type { Role } from '../core';
const props = withDefaults(
  defineProps<{ role?: Role; wheel?: boolean; disabled?: boolean }>(),
  {
    role: 'primary',
    wheel: false,
    disabled: false,
  },
);
import { channelsToHex } from '@salyra-ui/color-picker';
import { useTheme, useThemeStore } from './context';
const theme = useTheme(),
  store = useThemeStore();
let fields: import('../core').ThemeFieldRegistration | undefined;
onMounted(() => {
  fields = store.registerFields({ roles: [props.role] });
});
watch(
  () => [props.role],
  () => fields?.update({ roles: [props.role] }),
);
onBeforeUnmount(() => fields?.destroy());
</script>
<template>
  <ColorProvider
    :disabled="disabled || theme.disabled"
    :view="wheel ? 'wheel' : 'area'"
    :value="channelsToHex(theme.theme.structure.userPreset[role].DEFAULT)"
    @change="store.setColor(role, $event)"
    ><div class="tk-generator">
      <slot
        ><ColorViewSelect /><ColorSurface /><ColorFormatSelect /><ColorInput /><ColorMode
      /></slot></div
  ></ColorProvider>
</template>

// packages/theme-studio/svelte/ThemeGenerator.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { Role } from '../core';
  import {
    ColorSurface,
    ColorViewSelect,
    ColorWheel,
    ColorFormatSelect,
    ColorMode,
    ColorProvider,
    ColorArea,
    ColorSlider,
    ColorInput,
  } from '@salyra-ui/color-picker/svelte';
  import { channelsToHex } from '@salyra-ui/color-picker';
  import { useTheme, useThemeStore } from './context';
  let {
    role = 'primary',
    wheel = false,
    disabled = false,
    children,
    class: className = '',
  }: {
    children?: Snippet;
    class?: string;
    role?: Role;
    wheel?: boolean;
    disabled?: boolean;
  } = $props();
  const theme = useTheme(),
    store = useThemeStore();
  $effect(() => {
    const fields = store.registerFields({ roles: [role] });
    return fields.destroy;
  });
</script>

<ColorProvider
  disabled={disabled || $theme.disabled}
  view={wheel ? 'wheel' : 'area'}
  value={channelsToHex($theme.theme.structure.userPreset[role].DEFAULT)}
  onChange={(hex) => store.setColor(role, hex)}
>
  <div class="tk-generator {className}">
    {#if children}{@render children()}{:else}<ColorViewSelect /><ColorSurface
      /><ColorFormatSelect /><ColorInput /><ColorMode />{/if}
  </div>
</ColorProvider>
