// packages/theme-studio/vue/ThemeRoot.vue
<script setup lang="ts">
import { onMounted, onScopeDispose } from 'vue';
import {
  createThemeStore,
  mountThemeStore,
  type ThemeStore,
  type ThemeOptions,
} from '../core';
import { provideTheme } from './context';
defineOptions({ inheritAttrs: false });
const props = defineProps<{ store?: ThemeStore; options?: ThemeOptions }>(),
  initial = props.options,
  store = provideTheme(props.store ?? createThemeStore(initial));
let stop: (() => void) | undefined;
onMounted(() => (stop = mountThemeStore(store, initial?.storage, initial)));
onScopeDispose(() => stop?.());
defineExpose({ store });
</script>
<template><slot /></template>

// packages/theme-studio/svelte/ThemeRoot.svelte
<script lang="ts">
  import { onMount, untrack, type Snippet } from 'svelte';
  import {
    createThemeStore,
    mountThemeStore,
    type ThemeStore,
    type ThemeOptions,
  } from '../core';
  import { provideTheme } from './context';
  let {
    store: provided,
    options = {},
    children,
  }: {
    store?: ThemeStore;
    options?: ThemeOptions;
    children: Snippet;
  } = $props();
  const initial = untrack(() => options),
    store = provideTheme(untrack(() => provided ?? createThemeStore(initial)));
  onMount(() => mountThemeStore(store, initial.storage, initial));
</script>

{@render children()}
