// packages/theme-studio/react/ThemeName.tsx
'use client';
import { type ReactNode } from 'react';
import { suggestedThemeName, type ThemeStore } from '../core';
import { useTheme, useThemeStore } from './context';
export function ThemeName({
  label = 'Theme name',
  className = '',
  children,
}: {
  label?: string;
  className?: string;
  children?: (value: {
    name: string;
    suggestedName: string;
    setName: ThemeStore['setName'];
  }) => ReactNode;
}) {
  const state = useTheme(),
    store = useThemeStore(),
    suggestion = suggestedThemeName(state.theme);
  if (children)
    return (
      <>
        {children({
          name: state.theme.name,
          suggestedName: suggestion,
          setName: store.setName,
        })}
      </>
    );
  return (
    <label className={`tk-name ${className}`}>
      {label}
      <input
        maxLength={200}
        value={state.theme.name}
        placeholder={suggestion}
        onBlur={(e) => {
          if (!e.target.value) store.setName();
        }}
        onChange={(e) => store.setName(e.target.value)}
      />
      <small>Suggested: {suggestion}</small>
    </label>
  );
}

// packages/theme-kit/svelte/ThemeName.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { suggestedThemeName, type ThemeStore } from '../core';
  import { useTheme, useThemeStore } from './context';
  let { label = 'Theme name', class: className = '', children }: {
    label?: string; class?: string;
    children?: Snippet<[{ name: string; suggestedName: string; setName: ThemeStore['setName'] }]>;
  } = $props();
  const theme = useTheme(), store = useThemeStore();
  const suggestion = $derived(suggestedThemeName($theme.theme));
</script>
{#if children}{@render children({ name: $theme.theme.name, suggestedName: suggestion, setName: store.setName })}
{:else}
<label class={`tk-name ${className}`}>{label}<input maxlength={200} value={$theme.theme.name} placeholder={suggestion} onblur={(e) => { if (!e.currentTarget.value) store.setName(); }} oninput={(e) => store.setName(e.currentTarget.value)} /><small>Suggested: {suggestion}</small></label>
{/if}
