// packages/theme-studio/react/ThemeExport.tsx
'use client';
import { useEffect, useRef, type ReactNode } from 'react';
import {
  themeConfiguration,
  type ThemeConfiguration,
  type ThemeExportFormat,
  type TokenSelection,
} from '../core';
import { useTheme } from './context';
export function ThemeExport({
  format = 'json',
  selection,
  onChange,
  children,
  className = '',
}: {
  format?: ThemeExportFormat;
  selection?: TokenSelection;
  onChange?: (configuration: ThemeConfiguration) => void;
  children?: (configuration: ThemeConfiguration) => ReactNode;
  className?: string;
}) {
  const state = useTheme(),
    configuration = themeConfiguration(state, selection),
    selectionKey = JSON.stringify(selection),
    callback = useRef(onChange);
  callback.current = onChange;
  useEffect(
    () => callback.current?.(themeConfiguration(state, selection)),
    [
      state.theme,
      state.mode,
      state.modePreference,
      state.systemMode,
      selectionKey,
    ],
  );
  return children ? (
    <>{children(configuration)}</>
  ) : (
    <pre className={`tk-export ${className}`} aria-label="Theme configuration">
      {configuration[format]}
    </pre>
  );
}

// packages/theme-kit/svelte/ThemeExport.svelte
<script lang="ts">
  import { untrack, type Snippet } from 'svelte';
  import {
    themeConfiguration,
    type ThemeConfiguration,
    type ThemeExportFormat,
    type TokenSelection,
  } from '../core';
  import { useTheme } from './context';
  let {
    format = 'json',
    selection,
    onChange,
    children,
    class: className = '',
  }: {
    format?: ThemeExportFormat;
    selection?: TokenSelection;
    onChange?: (value: ThemeConfiguration) => void;
    children?: Snippet<[ThemeConfiguration]>;
    class?: string;
  } = $props();
  const theme = useTheme();
  const configuration = $derived(themeConfiguration($theme, selection));
  $effect(() => {
    const value = configuration;
    untrack(() => onChange?.(value));
  });
</script>

{#if children}{@render children(configuration)}{:else}<pre
    class="tk-export {className}"
    aria-label="Theme configuration">{configuration[format]}</pre>{/if}
