// packages/theme-studio/react/useThemeMode.tsx
'use client';
import { themeModeActions } from '../core';
import { useTheme, useThemeStore } from './context';
export function useThemeMode() {
  const state = useTheme(),
    store = useThemeStore();
  return {
    preference: state.modePreference,
    resolvedMode: state.mode,
    ...themeModeActions(store),
  };
}

// packages/theme-studio/angular/useThemeMode.ts
import { computed } from '@angular/core';
import { themeModeActions } from '../core';
import { useThemeStore } from './context';
import { useTheme } from './context';
export function useThemeMode() {
  const store = useThemeStore(),
    state = useTheme();
  return {
    preference: computed(() => state().modePreference),
    resolvedMode: computed(() => state().mode),
    ...themeModeActions(store),
  };
}
