// packages/theme-kit/svelte/ThemeProvider.svelte
<script lang="ts">
  import { onMount, untrack, type Snippet } from 'svelte';
  import {
    createThemeStore,
    mountThemeStore,
    type ThemeOptions,
    type ThemeStore,
  } from '../core';
  import { provideTheme, useTheme } from './context';
  let {
    children,
    options = {},
    store: provided,
    class: className = '',
  }: {
    children: Snippet;
    options?: ThemeOptions;
    store?: ThemeStore;
    class?: string;
  } = $props();
  const store = provideTheme(
      untrack(() => provided ?? createThemeStore(options)),
    ),
    theme = useTheme();
  onMount(() => mountThemeStore(store, options.storage, options));
</script>

<div
  class="tk-scope {className}"
  data-theme={$theme.theme.id}
  data-mode={$theme.mode}
  data-mode-preference={$theme.modePreference}
  data-theme-status={$theme.status}
  style={$theme.style}
>
  {@render children()}
</div>

// packages/theme-kit/vue/ThemeProvider.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount } from 'vue';
import {
  createThemeStore,
  mountThemeStore,
  type ThemeStore,
  type ThemeOptions,
} from '../core';
import { provideTheme, watchTheme } from './context';
const props = defineProps<{ options?: ThemeOptions; store?: ThemeStore }>();
const store = provideTheme(props.store ?? createThemeStore(props.options)),
  theme = watchTheme(store);
let cleanup: (() => void) | undefined;
onMounted(() => {
  cleanup = mountThemeStore(store, props.options?.storage, props.options);
});
onBeforeUnmount(() => cleanup?.());
</script>
<template>
  <div
    class="tk-scope"
    :data-theme="theme.theme.id"
    :data-mode="theme.mode"
    :data-theme-status="theme.status"
    :style="theme.style"
  >
    <slot />
  </div>
</template>
