// packages/theme-studio/vue/ThemeName.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useTheme, useThemeStore } from './context';
import { suggestedThemeName } from '../core';
withDefaults(defineProps<{ label?: string }>(), { label: 'Theme name' });
const theme = useTheme(),
  store = useThemeStore(),
  suggestion = computed(() => suggestedThemeName(theme.value.theme));
</script>
<template>
  <slot
    :name="theme.theme.name"
    :suggestedName="suggestion"
    :setName="store.setName"
  >
    <label class="tk-name"
      >{{ label
      }}<input
        maxlength="200"
        :value="theme.theme.name"
        :placeholder="suggestion"
        @blur="!($event.target as HTMLInputElement).value && store.setName()"
        @input="store.setName(($event.target as HTMLInputElement).value)"
      /><small>Suggested: {{ suggestion }}</small></label
    >
  </slot>
</template>

// packages/theme-studio/react/ThemeName.tsx
'use client';
import { type ReactNode } from 'react';
import { suggestedThemeName, type ThemeStore } from '../core';
import { useTheme, useThemeStore } from './context';
export function ThemeName({
  label = 'Theme name',
  className = '',
  children,
}: {
  label?: string;
  className?: string;
  children?: (value: {
    name: string;
    suggestedName: string;
    setName: ThemeStore['setName'];
  }) => ReactNode;
}) {
  const state = useTheme(),
    store = useThemeStore(),
    suggestion = suggestedThemeName(state.theme);
  if (children)
    return (
      <>
        {children({
          name: state.theme.name,
          suggestedName: suggestion,
          setName: store.setName,
        })}
      </>
    );
  return (
    <label className={`tk-name ${className}`}>
      {label}
      <input
        maxLength={200}
        value={state.theme.name}
        placeholder={suggestion}
        onBlur={(e) => {
          if (!e.target.value) store.setName();
        }}
        onChange={(e) => store.setName(e.target.value)}
      />
      <small>Suggested: {suggestion}</small>
    </label>
  );
}
