// packages/theme-kit/vue/ThemeExport.vue
<script setup lang="ts">
import { computed, watch, onMounted } from 'vue';
import {
  themeConfiguration,
  type ThemeConfiguration,
  type ThemeExportFormat,
  type TokenSelection,
} from '../core';
import { useTheme } from './context';
const props = withDefaults(
    defineProps<{ format?: ThemeExportFormat; selection?: TokenSelection }>(),
    { format: 'json' },
  ),
  emit = defineEmits<{ change: [value: ThemeConfiguration] }>();
const state = useTheme(),
  configuration = computed(() =>
    themeConfiguration(state.value, props.selection),
  );
onMounted(() => emit('change', configuration.value));
watch(
  [
    () => state.value.theme,
    () => state.value.mode,
    () => state.value.modePreference,
    () => state.value.systemMode,
    () => JSON.stringify(props.selection),
  ],
  () => emit('change', configuration.value),
);
</script>
<template>
  <slot :configuration="configuration">
    <pre class="tk-export" aria-label="Theme configuration">{{
      configuration[format]
    }}</pre>
  </slot>
</template>

// packages/theme-studio/react/ThemeExport.tsx
'use client';
import { useEffect, useRef, type ReactNode } from 'react';
import {
  themeConfiguration,
  type ThemeConfiguration,
  type ThemeExportFormat,
  type TokenSelection,
} from '../core';
import { useTheme } from './context';
export function ThemeExport({
  format = 'json',
  selection,
  onChange,
  children,
  className = '',
}: {
  format?: ThemeExportFormat;
  selection?: TokenSelection;
  onChange?: (configuration: ThemeConfiguration) => void;
  children?: (configuration: ThemeConfiguration) => ReactNode;
  className?: string;
}) {
  const state = useTheme(),
    configuration = themeConfiguration(state, selection),
    selectionKey = JSON.stringify(selection),
    callback = useRef(onChange);
  callback.current = onChange;
  useEffect(
    () => callback.current?.(themeConfiguration(state, selection)),
    [
      state.theme,
      state.mode,
      state.modePreference,
      state.systemMode,
      selectionKey,
    ],
  );
  return children ? (
    <>{children(configuration)}</>
  ) : (
    <pre className={`tk-export ${className}`} aria-label="Theme configuration">
      {configuration[format]}
    </pre>
  );
}
