// packages/theme-kit/vue/ThemeSelect.vue
<script setup lang="ts">
import { computed } from 'vue';
import { themeList, selectedThemeId, type Theme } from '../core';
import { useTheme, useThemeStore } from './context';
const props = withDefaults(
  defineProps<{ themes: readonly Theme[]; label?: string }>(),
  { label: 'Saved themes' },
);
const state = useTheme(),
  store = useThemeStore(),
  list = computed(() => themeList(props.themes)),
  value = computed(() => selectedThemeId(state.value.theme, list.value) ?? '');
function select(event: Event) {
  const theme = list.value.find(
    (theme) => theme.id === (event.target as HTMLSelectElement).value,
  );
  if (theme) store.setTheme(theme);
}
</script>
<template>
  <label class="cp-format tk-select"
    >{{ label
    }}<select :value="value" :disabled="!list.length" @change="select">
      <option value="" disabled>
        {{ list.length ? 'Custom theme' : 'No themes available' }}
      </option>
      <option v-for="theme in list" :key="theme.id" :value="theme.id">
        {{ theme.name }}
      </option>
    </select></label
  >
</template>

// packages/theme-studio/react/ThemeSelect.tsx
'use client';
import { selectedThemeId, themeList, type Theme } from '../core';
import { useTheme, useThemeStore } from './context';
export function ThemeSelect({
  themes,
  label = 'Saved themes',
  className = '',
}: {
  themes: readonly Theme[];
  label?: string;
  className?: string;
}) {
  const store = useThemeStore(),
    state = useTheme(),
    list = themeList(themes),
    value = selectedThemeId(state.theme, list) ?? '';
  return (
    <label className={`cp-format tk-select ${className}`}>
      {label}
      <select
        value={value}
        disabled={!list.length}
        onChange={(e) => {
          const theme = list.find((theme) => theme.id === e.target.value);
          if (theme) store.setTheme(theme);
        }}
      >
        <option value="" disabled>
          {list.length ? 'Custom theme' : 'No themes available'}
        </option>
        {list.map((theme) => (
          <option key={theme.id} value={theme.id}>
            {theme.name}
          </option>
        ))}
      </select>
    </label>
  );
}
