// packages/theme-studio/svelte/ThemeGenerator.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { Role } from '../core';
  import {
    ColorSurface,
    ColorViewSelect,
    ColorWheel,
    ColorFormatSelect,
    ColorMode,
    ColorProvider,
    ColorArea,
    ColorSlider,
    ColorInput,
  } from '@salyra-ui/color-picker/svelte';
  import { channelsToHex } from '@salyra-ui/color-picker';
  import { useTheme, useThemeStore } from './context';
  let {
    role = 'primary',
    wheel = false,
    disabled = false,
    children,
    class: className = '',
  }: {
    children?: Snippet;
    class?: string;
    role?: Role;
    wheel?: boolean;
    disabled?: boolean;
  } = $props();
  const theme = useTheme(),
    store = useThemeStore();
  $effect(() => {
    const fields = store.registerFields({ roles: [role] });
    return fields.destroy;
  });
</script>

<ColorProvider
  disabled={disabled || $theme.disabled}
  view={wheel ? 'wheel' : 'area'}
  value={channelsToHex($theme.theme.structure.userPreset[role].DEFAULT)}
  onChange={(hex) => store.setColor(role, hex)}
>
  <div class="tk-generator {className}">
    {#if children}{@render children()}{:else}<ColorViewSelect /><ColorSurface
      /><ColorFormatSelect /><ColorInput /><ColorMode />{/if}
  </div>
</ColorProvider>

// packages/theme-studio/react/ThemeGenerator.tsx
'use client';
import { channelsToHex } from '@salyra-ui/color-picker';
import {
  ColorFormatSelect,
  ColorInput,
  ColorMode,
  ColorProvider,
  ColorSurface,
  ColorViewSelect,
} from '@salyra-ui/color-picker/react';
import { useEffect, type ReactNode } from 'react';
import { type Role } from '../core';
import { useTheme, useThemeStore } from './context';
/** Compose your own layout with ColorProvider and useThemeStore().generate if preferred. */
export function ThemeGenerator({
  role = 'primary',
  wheel = false,
  disabled = false,
  children,
  className = '',
}: {
  children?: ReactNode;
  role?: Role;
  wheel?: boolean;
  disabled?: boolean;
  className?: string;
}) {
  const state = useTheme(),
    store = useThemeStore();
  useEffect(() => {
    const fields = store.registerFields({ roles: [role] });
    return fields.destroy;
  }, [store, role]);
  return (
    <ColorProvider
      disabled={disabled || state.disabled}
      view={wheel ? 'wheel' : 'area'}
      value={channelsToHex(state.theme.structure.userPreset[role].DEFAULT)}
      onChange={(hex) => store.setColor(role, hex)}
    >
      <div className={`tk-generator ${className}`}>
        {children ?? (
          <>
            <ColorViewSelect />
            <ColorSurface />
            <ColorFormatSelect />
            <ColorInput />
            <ColorMode />
          </>
        )}
      </div>
    </ColorProvider>
  );
}
