// packages/theme-kit/svelte/ThemeProvider.svelte
<script lang="ts">
  import { onMount, untrack, type Snippet } from 'svelte';
  import {
    createThemeStore,
    mountThemeStore,
    type ThemeOptions,
    type ThemeStore,
  } from '../core';
  import { provideTheme, useTheme } from './context';
  let {
    children,
    options = {},
    store: provided,
    class: className = '',
  }: {
    children: Snippet;
    options?: ThemeOptions;
    store?: ThemeStore;
    class?: string;
  } = $props();
  const store = provideTheme(
      untrack(() => provided ?? createThemeStore(options)),
    ),
    theme = useTheme();
  onMount(() => mountThemeStore(store, options.storage, options));
</script>

<div
  class="tk-scope {className}"
  data-disabled={$theme.disabled}
  data-theme={$theme.theme.id}
  data-mode={$theme.mode}
  data-mode-preference={$theme.modePreference}
  data-theme-status={$theme.status}
  style={$theme.style}
>
  <fieldset
    class="tk-provider-controls"
    disabled={$theme.disabled}
    inert={$theme.disabled}
    aria-disabled={$theme.disabled}
  >
    {@render children()}
  </fieldset>
</div>

// packages/theme-studio/react/ThemeProvider.tsx
'use client';
import { useEffect, useState, type CSSProperties, type ReactNode } from 'react';
import {
  createThemeStore,
  mountThemeStore,
  type ThemeOptions,
  type ThemeStore,
} from '../core';
import { Context, useTheme } from './context';
/** Options initialize this provider. Use store.setTheme for subsequent changes. */
export function ThemeProvider({
  children,
  className = '',
  style,
  store: provided,
  ...options
}: ThemeOptions & {
  children: ReactNode;
  className?: string;
  style?: CSSProperties;
  store?: ThemeStore;
}) {
  const [initial] = useState(options);
  const [store] = useState(() => provided ?? createThemeStore(initial));
  useEffect(
    () => mountThemeStore(store, initial.storage, initial),
    [store, initial],
  );
  return (
    <Context.Provider value={store}>
      <ThemeScope className={className} style={style}>
        {children}
      </ThemeScope>
    </Context.Provider>
  );
}

function ThemeScope({
  children,
  className,
  style,
}: {
  children: ReactNode;
  className: string;
  style?: CSSProperties;
}) {
  const state = useTheme();
  const variables = Object.fromEntries(
    state.style.split(';').map((p) => {
      const i = p.indexOf(':');
      return [
        p.slice(0, i) === 'color-scheme' ? 'colorScheme' : p.slice(0, i),
        p.slice(i + 1),
      ];
    }),
  );
  return (
    <div
      data-disabled={state.disabled}
      data-theme={state.theme.id}
      data-mode={state.mode}
      data-mode-preference={state.modePreference}
      data-theme-status={state.status}
      className={`tk-scope ${className}`}
      style={{ ...variables, ...style } as CSSProperties}
    >
      <fieldset
        className="tk-provider-controls"
        disabled={state.disabled}
        {...(state.disabled ? { inert: '' } : {})}
        aria-disabled={state.disabled}
      >
        {children}
      </fieldset>
    </div>
  );
}
